### ISSUE TITLE
Trident app fails !!!

### ISSUE THREAD

**Issue by EGYbkgo9449** [benjamin-42/Trident#11]
Hey, I've tried it with iPhone 5,3 9.3.2 but it just reboots and nothing happens, tried to change the offsets cuz I think some of them were wrong but it did the same thing !!!

**Comment by akemin-dayo** [comment]
If it is crashing [here](https://github.com/benjamin-42/Trident/blob/325a0caf893b92e02a0df62f2706f5eae737104a/Trident/exploit.c#L348) in `exploit.c`, then this appears to be part of an ongoing problem I'm investigating where Trident appears to have issues with some A6 SoC devices (like the `iPhone5,3`).

The addresses ("offsets") are correct (note that sometimes, there can be multiple correct possibilities), the issue lies elsewhere.

**Comment by EGYbkgo9449** [comment]
@angelXwind I think it fails in the read_pirmitive assertion

**Comment by aleondopeso** [comment]
my iPhone 5,2 9.3.1 reboots when i use trident and fail. Do you know why? @angelXwind i think that you can fix it!

**Comment by EGYbkgo9449** [comment]
@aleondopeso I think it's the same reason since the iPhone 5,2 & 5,3 share almost the same kernel

**Comment by EGYbkgo9449** [comment]
@angelXwind 
Here is my crash log (kernel panic):
http://pastebin.com/iaCZTc8e

**Comment by BrandonMStudios** [comment]
@angelXwind @EGYbkgo9449 I can confirm that this issue also occurs with the iPhone5,1 on iOS 9.3.3. I added my own offsets and I get a kernel panic as well.

**Comment by EGYbkgo9449** [comment]
@BrandonMStudios 
Then I think it happens to the iPhone 5,1 -----> 5,4 (iPhone 5 & 5C)

**Comment by 1Conan** [comment]
#32 Works for me though. No panic. 'w00t root' message.

**Comment by benjamin-42** [comment]
Great, thank you @1Conan

**Comment by EGYbkgo9449** [comment]
But it doesn't work for the 5,3 !!!

**Comment by 1Conan** [comment]
@benjamin-42 Just got this today, it crashes at times. But most of the time it works.

**Comment by EGYbkgo9449** [comment]
But it "always" happens to the iPhone 5,3 9.3.2 😔
